[package]
name = "dnet-rpc"
version = "0.1.2"
edition = "2021"
authors = ["zduny <dzduniak@gmail.com>"]
description = "Remote Procedure Call over dnet transports"
license = "MIT"
repository = "https://github.com/druntime/dnet"
documentation = "https://docs.rs/dnet-rpc/"
keywords = ["rpc", "message", "message-passing", "communication"]
categories = ["network-programming"]

[features]
default = []
logging = ["dnet-base/logging", "dnet-tests/logging"]

[dependencies]
dnet-base = { workspace = true }
dnet-macros = { workspace = true }
dnet-utils = { workspace = true }
dportable = { workspace = true }
serde = { workspace = true }
pin-project = { workspace = true }
futures = { workspace = true }
atomic-counter = "1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
dnet-js = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = "0.3"

[dev-dependencies]
dnet-tests = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1", features = ["full"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
dnet-codecs = { workspace = true }
wasm-bindgen-test = { workspace = true }
