[book]
title = "The `dnet` Book"
authors = ["zduny <dzduniak@gmail.com>"]
language = "en"

[output.html]
git-repository-url = "https://github.com/druntime/dnet"

[output.html.playground]
runnable = false
